### ISSUE TITLE
Any clue what to do with RuntimeError: CUDA out of memory. Tried to allocate…

### ISSUE THREAD

**Issue by jonasjohansson** [justin-bennington/S2ML-Art-Generator#5]
After running the Colab once, on the second try, I get the message that CUDA is out of memory. What is the best practice to reset this? I've tried a few different solutions from StackOverflow and forums, but none that has worked.

**Comment by ROSCOLUX302** [comment]
was there ever a solution to this issue? I'm getting the same error. Do I just need to hope that Colab gives me a better GPU than a K80?
